"""initial_tables

Revision ID: 239ba0921e0a
Revises: 
Create Date: 2026-03-28 02:41:57.746760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239ba0921e0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_gateway_id', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'orders', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    op.drop_column('orders', 'payment_gateway_id')
    # ### end Alembic commands ###
